import { Permission, Role } from './enum.constant'

export const rolePermissionsMap: Record<Role, Permission[]> = {
  [Role.PASSENGER]: [
    Permission.SEAT_BOOK,
    Permission.ACCOUNT_RESET_PASSWORD,
    Permission.SEAT_UNBOOK,
    Permission.CHECKIN_CREATE,
    Permission.CHECKIN_READ_OWN,
    Permission.LOCATION_UPDATE_SELF,
    Permission.BAGGAGE_READ,
    Permission.BAGGAGE_UPDATE,
    Permission.BAGGAGE_DELETE,
    Permission.ACCOUNT_CHANGE_PASSWORD,
  ],
  [Role.ADMIN]: [
    Permission.AIRLINE_CREATE,
    Permission.AIRLINE_UPDATE,
    Permission.AIRLINE_DELETE,
    Permission.AIRLINE_MANAGE_FLIGHTS,
    Permission.FLIGHT_CREATE,
    Permission.FLIGHT_UPDATE,
    Permission.FLIGHT_DELETE,
    Permission.FLIGHT_CANCEL,
    Permission.FLIGHT_DELAY,
    Permission.FLIGHT_CHANGE_GATE,
    Permission.EMPLOYEE_CREATE,
    Permission.EMPLOYEE_DELETE,
    Permission.EMPLOYEE_READ_ALL,
    Permission.EMPLOYEE_PROMOTE,
    Permission.EMPLOYEE_UPDATE_ROLE,
    Permission.USER_CREATE,
    Permission.USER_DELETE,
    Permission.USER_UPDATE,
    Permission.USER_VIEW,
    Permission.ADMIN_ACCESS,
    Permission.ADMIN_MANAGE_USERS,
    Permission.AIRPORT_CREATE,
    Permission.AIRPORT_UPDATE,
    Permission.AIRPORT_DELETE,
    Permission.TERMINAL_CREATE,
    Permission.TERMINAL_UPDATE,
    Permission.TERMINAL_DELETE,
    Permission.GATE_CREATE,
    Permission.GATE_UPDATE,
    Permission.GATE_DELETE,
    Permission.TICKET_VIEW,
    Permission.LOCATION_UPDATE_AIRLINE,
    Permission.LOCATION_UPDATE_AIRPORT,
    Permission.ACCOUNT_CHANGE_PASSWORD,
  ],
  [Role.AIRLINE_MANAGER]: [
    Permission.AIRLINE_MANAGE_FLIGHTS,
    Permission.AIRLINE_READ,
    Permission.FLIGHT_CREATE,
    Permission.FLIGHT_UPDATE,
    Permission.FLIGHT_DELETE,
    Permission.FLIGHT_CANCEL,
    Permission.FLIGHT_DELAY,
    Permission.FLIGHT_CHANGE_GATE,
    Permission.SEAT_CREATE,
    Permission.SEAT_UPDATE,
    Permission.SEAT_DELETE,
    Permission.EMPLOYEE_READ,
    Permission.USER_UPDATE,
    Permission.TICKET_VIEW,
    Permission.LOCATION_UPDATE_SELF,
    Permission.ACCOUNT_CHANGE_PASSWORD,
  ],
  [Role.MANAGER]: [
    Permission.EMPLOYEE_READ_ALL,
    Permission.EMPLOYEE_DELETE,
    Permission.FLIGHT_CREW_CREATE,
    Permission.FLIGHT_CREW_DELETE,
    Permission.GATE_CREATE,
    Permission.GATE_UPDATE,
    Permission.GATE_DELETE,
    Permission.TICKET_UPDATE,
    Permission.TICKET_DELETE,
    Permission.USER_UPDATE,
    Permission.USER_DELETE,
    Permission.USER_VIEW,
    Permission.LOCATION_UPDATE_SELF,
    Permission.ACCOUNT_CHANGE_PASSWORD,
  ],
  [Role.PILOT]: [
    Permission.ACCOUNT_CHANGE_PASSWORD,
    Permission.LOCATION_UPDATE_SELF,
  ],
  [Role.SECURITY]: [
    Permission.EMPLOYEE_READ,
    Permission.BAGGAGE_READ,
    Permission.BAGGAGE_READ_ALL,
    Permission.TICKET_VIEW,
    Permission.ACCOUNT_CHANGE_PASSWORD,
    Permission.LOCATION_UPDATE_SELF,
  ],
  [Role.GROUND_STAFF]: [
    Permission.TICKET_VIEW,
    Permission.LOCATION_UPDATE_SELF,
    Permission.ACCOUNT_CHANGE_PASSWORD,
  ],
  [Role.FLIGHT_ATTENDANT]: [
    Permission.TICKET_VIEW,
    Permission.ACCOUNT_CHANGE_PASSWORD,
    Permission.LOCATION_UPDATE_SELF,
  ],
}
